language: node_js
node_js:
  - "6"
addons:
  firefox: "46.0.1"
install:
  - npm install -g webpack
  - npm install -g http-server
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - npm run build
  - npm run test
branches:
  only:
    - master
